standard = "2008"

[libraries]
defaultlib.files = [
    "pb_APP_log_comb.sim/sim_1/behav/xsim/**/*.vhd",
]
defaultlib.exclude = [
    "**/*.vdb", # compiled binaries
    "**/xsim.dir/**", # simulation-specific internal files
]

UNISIM.files = [
    "/opt/Xilinx/Vivado/2023.1/data/vhdl/src/unisims/unisim_VCOMP.vhd",
]
UNISIM.is_third_party = true

[lint]
unused = "error"
unnecessary_work_library = false
