standard = "2008"

[libraries]
defaultlib.files = [
    "pb_APP_log_comb.srcs/**/*.vhd",
]
defaultlib.exclude = [
    "**/*.vdb",       # compiled binaries
    "**/xsim.dir/**", # simulation-specific internal files
]

UNISIM.files = [
    "/tools/Xilinx/Vivado/2020.2/data/vhdl/src/unisims/unisim_VCOMP.vhd",
]
UNISIM.is_third_party = true

IEEE.files = [
  "/tools/ghdl/libraries/ieee2008/*.vhdl",
  "/tools/ghdl/libraries/ieee/*.vhdl",
  # "/tools/ghdl
]
IEEE.is_third_party = true



[lint]
unused = "error"
unnecessary_work_library = false
